apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  JWT_SECRET_KEY: my-super-secret-long-random-key-for-muchtodo-app
  MONGO_URI: mongodb://root:example@mongodb:27017/?authSource=admin&directConnection=true
