apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: muchtodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: muchtodo-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_NAME
            - name: JWT_EXPIRATION_HOURS
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: JWT_EXPIRATION_HOURS
            - name: ENABLE_CACHE
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: ENABLE_CACHE
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: LOG_FORMAT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
